all:
	c++ -Wall -Wextra -Werror -std=c++98 main.cpp Bureaucrat.cpp AForm.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp Intern.cpp -o intern
clean:
	rm -f intern
re: clean all
